/* Joomla module import */
INSERT IGNORE INTO `#__csvi_availablefields` (`csvi_name`, `component_name`, `component_table`, `component`, `action`) VALUES
('skip', 'skip', 'modules', 'com_modules', 'import'),
('combine', 'combine', 'modules', 'com_modules', 'import'),
('asset_id', 'asset_id', 'modules', 'com_modules', 'import'),
('title', 'title', 'modules', 'com_modules', 'import'),
('note', 'note', 'modules', 'com_modules', 'import'),
('content', 'content', 'modules', 'com_modules', 'import'),
('ordering','ordering', 'modules', 'com_modules', 'import'),
('position', 'position', 'modules', 'com_modules', 'import'),
('checked_out', 'checked_out', 'modules', 'com_modules', 'import'),
('checked_out_time','checked_out_time', 'modules', 'com_modules', 'import'),
('publish_up','link_parent_category', 'modules', 'com_modules', 'import'),
('publish_down', 'publish_down', 'modules', 'com_modules', 'import'),
('published', 'published', 'modules', 'com_modules', 'import'),
('module','module', 'modules', 'com_modules', 'import'),
('access','access', 'modules', 'com_modules', 'import'),
('showtitle', 'showtitle', 'modules', 'com_modules', 'import'),
('params','params', 'modules', 'com_modules', 'import'),
('client_id','client_id', 'modules', 'com_modules', 'import'),
('language', 'language', 'modules', 'com_modules', 'import'),
('menuid', 'menuid', 'modules', 'com_modules', 'import'),
('moduleid', 'moduleid', 'modules', 'com_modules', 'import'),
('menu_alias', 'menu_alias', 'modules', 'com_modules', 'import'),
('module_delete', 'module_delete', 'modules', 'com_modules', 'import'),

/* Joomla module export */
('custom', 'custom', 'modules', 'com_modules', 'export'),
('asset_id', 'asset_id', 'modules', 'com_modules', 'export'),
('title', 'title', 'modules', 'com_modules', 'export'),
('note', 'note', 'modules', 'com_modules', 'export'),
('content', 'content', 'modules', 'com_modules', 'export'),
('ordering','ordering', 'modules', 'com_modules', 'export'),
('position', 'position', 'modules', 'com_modules', 'export'),
('checked_out', 'checked_out', 'modules', 'com_modules', 'export'),
('checked_out_time','checked_out_time', 'modules', 'com_modules', 'export'),
('publish_up','link_parent_category', 'modules', 'com_modules', 'export'),
('publish_down', 'publish_down', 'modules', 'com_modules', 'export'),
('published', 'published', 'modules', 'com_modules', 'export'),
('module','module', 'modules', 'com_modules', 'export'),
('access','access', 'modules', 'com_modules', 'export'),
('showtitle', 'showtitle', 'modules', 'com_modules', 'export'),
('params','params', 'modules', 'com_modules', 'export'),
('client_id','client_id', 'modules', 'com_modules', 'export'),
('language', 'language', 'modules', 'com_modules', 'export'),
('menuid', 'menuid', 'modules', 'com_modules', 'export'),
('moduleid', 'moduleid', 'modules', 'com_modules', 'export'),
('menu_alias', 'menu_alias', 'modules', 'com_modules', 'export');